version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      # - POSTGRES_DB=my_store
      - POSTGRES_DB=railway
      # - POSTGRES_USER=nico
      - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=admin123
      - POSTGRES_PASSWORD=MjPpshpy75pQwH9x6vDv
    ports:
      # - 5432:5432
      - 6155:6155
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      # - MYSQL_DATABASE=my_store
      - MYSQL_DATABASE=railway
      - MYSQL_USER=root
      # - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=MjPpshpy75pQwH9x6vDv
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      # - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=MjPpshpy75pQwH9x6vDv
      - PMA_HOST=mysql
    ports:
      - 8080:80
